name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC",
              os: windows-latest,
              cxx: "cl",
            }
          - {
              name: "Ubuntu gcc",
              os: ubuntu-latest,
              cxx: "g++",
            }
          - {
              name: "MacOS clang",
              os: macos-latest,
              cxx: "clang++",
            }
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Run CMake (*nix)
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
        if: (contains(matrix.config.os, 'windows') != true)
      - name: Run CMake (Windows)
        run: |
          mkdir build
          cd build
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
        shell: cmd
        if: (contains(matrix.config.os, 'windows') == true)
      - name: Build (*nix)
        run: |
          cd build
          ninja
        if: (contains(matrix.config.os, 'windows') != true)
      - name: Build (Windows)
        run: |
          cd build
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          ninja
        shell: cmd
        if: (contains(matrix.config.os, 'windows') == true)
